# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
google_analytics: p05wn
title: 0s_W

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: p05wnable blog

description: Welcome to my blog
author:
  name: 0s_W
  email: p05wnable@gmail.com
  github: p05wn
  twitter: 0s_W1337
  bio: digging in to the unknown
  email_md5: 0be7052f6f65b891fc1f5f1148cf43b6

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-toc

jekyll_toc:
  min_level: 1      # h1부터 인식
  max_level: 3      # h3까지 인식
  ordered_list: false  # 불릿 리스트로 (true면 1.1.1 번호 방식)
  no_toc_section_class: "no_toc_section"
