header_pages:
  - index.markdown
  - 1day.markdown
  - ctf.markdown
  - about.markdown

style: dark # dark (default), light, hacker, or nord
listen_for_clients_preferred_style: true # false (default) or true
disable_google_fonts: false
robots: NONOINDEX

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed